#! configuration/base.yaml
application:
  port: 8000
  host: 127.0.0.1
  redis_uri: "redis://127.0.0.1:6379"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
